---    
-   name: Template nginx config to server
    template:
        src: grafana.ini.j2
        dest: /tmp/grafana.ini
        force: yes

-   name: Pull from dockerhub grafana/grafana:8.2.4
    command: docker pull grafana/grafana:8.2.4

-   name: Container for grafana/grafana:8.2.4
    docker_container:
        name: "grafana"
        image: "grafana/grafana:8.2.4"
        restart_policy: "always"
        volumes:
            - "/tmp/grafana.ini:/etc/grafana/grafana.ini"
            - "/tmp/dashboards:/var/lib/grafana/dashboards"
        network_mode: host
        env:
            GF_SECURITY_ADMIN_PASSWORD: admin
