version: '3'
services:
  dev_mysql:
    image: mysql/mysql-server:5.7
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=password
  prod:
    image: sandrakullar/microblog:new
    links:
      - dev_mysql
    environment:
      - SECRET_KEY=my-secret-key
      - DATABASE_URL=mysql+pymysql://microblog:password@dev_mysql/microblog
    ports:
      - 8000:5000
    restart: always
  test_mysql:
    image: mysql/mysql-server:5.7
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=password
  test:
      volumes:
          - .:/home/microblog
          - /home/microblog/.venv
      build: 
          context: .
          dockerfile: ./docker/Dockerfile_test