version: '3'
services:
    mysql:  
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=password
        volumes:
            - '/var/lib/mysql:/var/lib/mysql'
    prod:
        image: sk/microblog:latest
        build: 
            dockerfile: docker/Dockerfile_prod
            context: .
        container_name: 'microblog'
        environment:
            - FLASK_APP=microblog.py
            - SECRET_KEY=my-secret-key
            - DATABASE_URL=mysql+pymysql://microblog:password@mysql-server/microblog 
        ports:
            - '8000:5000'

        links:
            - mysql:mysql-server
        restart: 'always'
    test:
        volumes:
            - .:/home/microblog
            - /home/microblog/.venv
        build: 
            context: .
            dockerfile: ./docker/Dockerfile_test