global:
  scrape_interval:  30s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['52.164.124.42:9104']