---
- name: Download and unarchive node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/azureuser
    remote_src: yes

- name: Create a node exporter user
  user:
    name: "node_exporter"
    system: yes
    create_home: no
    state: present

- name: Copy node_exporter to directory
  copy:
    src: /home/azureuser/node_exporter-1.0.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: "node_exporter"
    group: "node_exporter"
    mode: '0755'
    remote_src: yes

- name: remove tmp dir
  file:
    path: /home/azureuser/node_exporter-1.0.1.linux-amd64/
    state: absent

- name: Create and setup node_exporter service
  template:
    src: ./templates/node_exporter.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "azureuser"
    group: "azureuser"
    mode: '0755'

- name: Reload daremon 
  systemd:
    daemon_reload: yes

- name: Start node_exporter
  systemd:
    state: started
    name: node_exporter