FROM python:3.8

WORKDIR /home/microblog
COPY test1.sh .
COPY requirements ./requirements

RUN python -m venv .venv \
 && .venv/bin/pip3 install -r requirements/test.txt \
 && .venv/bin/pip3 install py pytest coverage pylint \
 && chmod +x test1.sh


ENTRYPOINT [ "./test1.sh" ]