# Gather facts from remote instance and set as hosts
---
-   hosts: local
    connection: local
    gather_facts: False
    collections:
        - azure.azcollection
    roles:
        - gather_vm_instances
