---
-   hosts:
    -   monitoring
    remote_user: azureuser
    become: yes
    become_method: sudo
    vars:
      ansible_python_interpreter: /usr/bin/python3
    roles:
        - docker
        - node_exporter
        - prometheus
        - monitoring
